#pragma once
#include <vector>
#include <opencv2/opencv.hpp>
#include "track/YoloTrackConfig.h"

 namespace yolo {
    /**
     * @brief
     * base class for all track algorithms.
     * 
     * supports:
     * 1. algorithms depends on pure physical information: such as sort, bytetrack
     * 2. algorithms depends on feature information      : such as deepsort
    */
    class BaseTrackAlgo {
    private:
        /* data */
    protected:
        YoloTrackConfig _cfg;
    public:
        BaseTrackAlgo(const YoloTrackConfig& cfg);
        ~BaseTrackAlgo();

        /**
         * @brief
         * run track algorithm with physical & feature information,
         * and return the track ids.
         * 
         * @param boxes [physical information] bounding boxes to be used while tracking.
         * @param embeddings [feature information] embeddings to be used while tracking.
         * @param track_ids track ids generated by algorithm.
         * 
         * @note
         * assert(boxes.size() == embeddings.size())
         * 
         * just ignore embeddings parameter(pass empty vector) if the algorithm relys on physical information only.
        */
        virtual void run(
            const std::vector<cv::Rect>& boxes, 
            const std::vector<std::vector<float>>& embeddings, 
            std::vector<int>& track_ids) = 0;
    };
 }